spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet
    username: wallet
    password: wallet
  flyway:
    locations: classpath:db/migration
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/wallet
    username: wallet
    password: wallet
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath*:db/postgresql/schema.sql

logging:
  level:
    org.springframework.r2dbc: debug
    io.r2dbc.postgresql: DEBUG
    root: info