
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet
    username: wallet
    password: wallet
  flyway:
    locations: classpath:db/migration
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/wallet
    username: wallet
    password: wallet

  rabbitmq:
    host: localhost
    port: 5672
    username: closeSea
    password: closeSeaP@ssword

  data:
    redis:
      cluster:
        nodes: localhost:6379,localhost:6380,localhost:6381,localhost:6382,localhost:6383,localhost:6384,localhost:6385,localhost:6386,localhost:6387,localhost:6388
        max-redirects: 3
        password: bitnami
        timeout: 500ms
        connect-ip: localhost
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

#  sql:
#    init:
#      mode: always
#      schema-locations: classpath*:db/postgresql/schema.sql
logging:
  level:
    org.springframework.r2dbc: debug
    io.r2dbc.postgresql: DEBUG
#    root: info

auth:
  uri: "http://localhost:8081/v1/auth"
nft:
  uri: "http://localhost:8082/v1/nft"
admin:
  uri: "http://localhost:8084/v1/admin"
server:
  port: 8083