spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet
    username: wallet
    password: wallet
  flyway:
    locations: classpath:db/migration
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/wallet
    username: wallet
    password: wallet
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath*:db/postgresql/schema.sql
  rabbitmq:
    host: localhost
    port: 5672
    username: closeSea
    password: closeSeaP@ssword
    queues:
      nft: "nftQueue"
    template:
      exchange: "exchange"
      routing-key: "routingKey"

logging:
  level:
    org.springframework.r2dbc: debug
    io.r2dbc.postgresql: DEBUG
    root: info

auth:
  uri: "http://localhost:8081/v1/auth"
nft:
  uri: "http://localhost:8082/v1/nft"